package enidh.cd.web;

import enidh.cd.utils.ExceptionsUtils;
import enidh.cd.utils.ILogger;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.Socket;
import javax.net.ssl.SSLSocketFactory;
import javax.swing.SwingUtilities;

/**
 *
 * @author cgonc
 */
public class SimpleBrowser 
        extends javax.swing.JFrame 
        implements ILogger {

    private Socket s;
    
    private String lastTitle;
    
    class Receiver extends Thread {
        private final Socket s;
        private final ILogger logger;
        private final String title;
        
        public Receiver(Socket s, ILogger logger, String title) {
            this.s = s;
            this.logger = logger;
            this.title = title;
        }
        
        @Override
        public void run() {
            try {
                BufferedReader in = new BufferedReader( new InputStreamReader( this.s.getInputStream() ) );
                
                String currentLine;
                
                // Read header response
                while ( (currentLine=in.readLine()).length()!= 0 ) {
                    SimpleBrowser.this.jTextAreaResponse.append( currentLine + "\r\n" );
                }
                
                // Read page
                WebPageDisplay display = new WebPageDisplay( this.title, "" );
                while ( (currentLine=in.readLine())!=null ) {
                    display.appendContent( currentLine + "\r\n" );
                }

                this.logger.log( "Receiver is ending." );
                
                this.s.close();
            }
            catch (Exception ex) {
                ExceptionsUtils.showException( SimpleBrowser.this, ex, "Erro ao ler resposta" );
            }
        }
    }
    
    private void handleConnection() {
        try {
            String hostName = this.jTextFieldHostName.getText();
            int portNumber = Integer.parseInt( this.jTextFieldPortNumber.getText() );
            
            this.lastTitle = String.format( "%s:%d", hostName, portNumber );
            
            if ( this.jCheckBoxUseSSL.isSelected() ) {
                SSLSocketFactory factory=(SSLSocketFactory) SSLSocketFactory.getDefault();
                this.s = factory.createSocket(hostName,portNumber);
            }
            else {
                this.s = new Socket(hostName, portNumber );
            }

            this.log( "Connection to %s:%d established",  hostName, portNumber );
        }
        catch (Exception ex) {
            ExceptionsUtils.showException( this, ex, "Erro ao estabelecer ligação" );   
        }
    }
    
    private void handleRequest() {
        try {
            OutputStream out = this.s.getOutputStream();
            
            String requestAsString = 
                    (this.jTextAreaRequest.getText() + "\n").replaceAll( "\n", "\r\n" ) + 
                    "\r\n";
            byte[] resquestAsByteArray = requestAsString.getBytes();
            out.write( resquestAsByteArray  );
            
            (new Receiver( this.s, (ILogger)this, this.lastTitle  )).start();
            
            this.log( "Request is done." );
        }
        catch (Exception ex) {
            ExceptionsUtils.showException( this, ex, "Erro ao enviar pedido" );   
        }
    }
    
    private void handleClearResponseArea() {
        this.jTextAreaResponse.setText( "" );
    }
    
    private void handleClearLoggingArea() {
        this.jTextAreaLogging.setText( "" );
    }
    
    private void myInitComponents() {
    }
    
    @Override
    public String log(String rawMessage, Object... args) {
        
        String formatedMessage = String.format(rawMessage, args);
        
        Runnable update = new Runnable() {
            @Override
            public void run() {
                SimpleBrowser.this.jTextAreaLogging.append( formatedMessage + "\r\n" );
            }
        };
        if (SwingUtilities.isEventDispatchThread() ) {
            update.run();
        }
        else {
            SwingUtilities.invokeLater(update);
        }
        
        return formatedMessage;
    }

    /**
     * Creates new form SimpleBrowser
     */
    public SimpleBrowser() {
        initComponents();
        
        myInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldHostName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPortNumber = new javax.swing.JTextField();
        jCheckBoxUseSSL = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaRequest = new javax.swing.JTextArea();
        jButtonMakeRequest = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaResponse = new javax.swing.JTextArea();
        jButtonConnect = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaLogging = new javax.swing.JTextArea();
        jButtonClearResponse = new javax.swing.JButton();
        jButtonClearLogging = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Web Address");

        jTextFieldHostName.setText("www.enautica.pt");

        jLabel2.setText(":");

        jTextFieldPortNumber.setText("80");

        jCheckBoxUseSSL.setText("Use SSL");

        jLabel3.setText("Request");

        jTextAreaRequest.setColumns(20);
        jTextAreaRequest.setRows(5);
        jTextAreaRequest.setText("GET / HTTP/1.1\nHost: enautica");
        jScrollPane1.setViewportView(jTextAreaRequest);

        jButtonMakeRequest.setText("Make Request");
        jButtonMakeRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMakeRequestActionPerformed(evt);
            }
        });

        jLabel4.setText("Response");

        jTextAreaResponse.setEditable(false);
        jTextAreaResponse.setColumns(20);
        jTextAreaResponse.setRows(5);
        jScrollPane2.setViewportView(jTextAreaResponse);

        jButtonConnect.setText("Make Connection");
        jButtonConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnectActionPerformed(evt);
            }
        });

        jLabel5.setText("Logging");

        jTextAreaLogging.setEditable(false);
        jTextAreaLogging.setColumns(20);
        jTextAreaLogging.setRows(5);
        jScrollPane3.setViewportView(jTextAreaLogging);

        jButtonClearResponse.setText("Clear Response");
        jButtonClearResponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearResponseActionPerformed(evt);
            }
        });

        jButtonClearLogging.setText("Clear Logging");
        jButtonClearLogging.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearLoggingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jButtonMakeRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldHostName, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPortNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxUseSSL, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConnect, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                    .addComponent(jScrollPane3)
                    .addComponent(jButtonClearResponse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonClearLogging, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldHostName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPortNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxUseSSL)
                    .addComponent(jButtonConnect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMakeRequest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonClearResponse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonClearLogging)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMakeRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMakeRequestActionPerformed
        handleRequest();
    }//GEN-LAST:event_jButtonMakeRequestActionPerformed

    private void jButtonConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectActionPerformed
        handleConnection();
    }//GEN-LAST:event_jButtonConnectActionPerformed

    private void jButtonClearResponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearResponseActionPerformed
        handleClearResponseArea();
    }//GEN-LAST:event_jButtonClearResponseActionPerformed

    private void jButtonClearLoggingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearLoggingActionPerformed
        handleClearLoggingArea();
    }//GEN-LAST:event_jButtonClearLoggingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClearLogging;
    private javax.swing.JButton jButtonClearResponse;
    private javax.swing.JButton jButtonConnect;
    private javax.swing.JButton jButtonMakeRequest;
    private javax.swing.JCheckBox jCheckBoxUseSSL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaLogging;
    private javax.swing.JTextArea jTextAreaRequest;
    private javax.swing.JTextArea jTextAreaResponse;
    private javax.swing.JTextField jTextFieldHostName;
    private javax.swing.JTextField jTextFieldPortNumber;
    // End of variables declaration//GEN-END:variables
}
