package enidh.cd.web;

import enidh.cd.utils.ExceptionsUtils;
import javax.swing.text.Document;


/**
 *
 * @author cgonc
 */
public class WebPageDisplay extends javax.swing.JFrame {
        
    public WebPageDisplay(String title, String contents) {
        initComponents( /*contents*/ );
        
        this.setTitle( title );
        
        this.setVisible( true );
    }
    
    public void setContent(String content) {
        this.jEditorPane1.setText( content );
        this.pack();
    }
    
    public void appendContent(String content) {
        try {
            Document doc = this.jEditorPane1.getDocument();
            doc.insertString(doc.getLength(), content, null);            
            this.pack();
        }
        catch(Exception exc) {
            ExceptionsUtils.showException( this, exc, "Erro ao adicionar conteudo" );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jEditorPane1.setEditable(false);
        jEditorPane1.setContentType("text/html"); // NOI18N
        jScrollPane1.setViewportView(jEditorPane1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
