FROM python:3.10-slim

WORKDIR /app

# Instala as ferramentas para a API e Base de Dados
RUN pip install --no-cache-dir flask psycopg2-binary flasgger

COPY . /app

# Arranca a API REST
CMD ["python", "ApiServer.py"]